### PR TITLE
Automatically create config when it doesn't exist

### PR DESCRIPTION
**Pull request by clinch**
Implementation for #1 . Also put in a bit of extra bullet proofing.

No tests written. There wasn't an existing framework to follow.

### CODE REVIEW

**Comment by nablaa** [comment]
Thank you for the contribution! Could you also update the `README.md`?  Currently it states that

```
Before starting the server, a config file must be created.
```

**Comment by clinch** [comment]
I've committed a new version. I think this should run fine now.

**Comment by nablaa** [comment]
Thank you! Looks good, merged.

Would you need a new version of this package to npm with this feature included?

**Comment by clinch** [comment]
Not necessarily. I'll leave that up to you, whenever you want to publish it.

**Comment by nablaa** [comment]
This project hasn't seen that much development lately, I might as well just make a new version.

**Pull request merged**
